logs_root_path: code/data_volume/pdc/logs_proto
object_id: "itri_book"
train:
- "2019-03-04-16-57-18"
- "2019-03-04-17-01-25"

test:
- "2019-03-04-16-52-58"
- "2019-03-04-17-06-08"
evaluation_labeled_data_path: 
- "code/data_volume/pdc/evaluation_labeled_data/itri_book_not_yet_configure.yaml"
