logs_root_path: code/data_volume/pdc/logs_proto
object_id: "itri_stapler"
train:
- "2019-03-04-17-40-53"
- "2019-03-04-17-45-34"

test:
- "2019-03-04-17-34-46"
- "2019-03-04-17-49-50"
evaluation_labeled_data_path: 
- "code/data_volume/pdc/evaluation_labeled_data/itri_stapler_not_yet_configure.yaml"
